### ISSUE TITLE
INotify not working on osx

### ISSUE THREAD

**Issue by h-leth** [squirrel-writer/squirrel#3]
Seems Inotify doesn´t work with osx. So the `watch` daemon doesn't work on my machine. 
Trying to rewrite the code to make it work with [watchdog](https://pypi.org/project/watchdog/)

Should be working with Linux, FreeBSD and Windows too

If I make it work I'll make a pull requests and you can implement it if you want.
It's a learning project for me, so not sure if I'll manage to make it work.

**Comment by zeddo123** [comment]
Thanks for your interest 🙂 

I that be great to have at least osx support. Since I started squirrel as a holiday project, I didn't pay much attention to compatibility.

Having said that, Inofity isn't used that much in the project (maybe in the future, it could have more importance), so we might remove the inotify part and count every x minutes. *something reconsider*
